config/routes.rb
Konnyaku::Application.routes.draw do

  root 'welcome#index'

  controller :welcome do
    get :index
    get :dashboard
    get :search
  end

  controller :sessions do
    get :sign_in, action: :new
    post :sessions, action: :create
    delete :sign_out, action: :destroy
  end

  resources :categories
  resources :posts do
    post :markdown, on: :collection
    resources :comments, only: [:create, :destroy]
    resources :versions, only: [:index, :show]
  end
  resources :tags, only: [:index, :show]

  resources :files, only: [:index, :create, :destroy], controller: :uploads, as: :uploads

end

app/views/shared/_admin_menu.html.erb
<li><%= link_to :new_post do %><i class="icon-plus"></i> <%= t(:new_post) %><% end %></li>
<li><%= link_to :posts do %><i class="icon-book"></i> <%= t(:posts) %><% end %></li>
<li><%= link_to :categories do %><i class="icon-folder-open-alt"></i> <%= t(:categories) %><% end %></li>
<li><%= link_to :uploads do %><i class="icon-upload-alt"></i> <%= t(:uploads) %><% end %></li>
<li><%= link_to :sign_out, method: 'delete' do %><i class="icon-signout"></i> <%= t(:sign_out) %><% end %></li>

app/views/shared/_aside.html.erb
<div class="span3">
  <div class="well well-small">
    <ul class="nav nav-list">
      <li class="nav-header">
        <%= t(:author) %>
      </li>
      <li class="divider"></li>

      <li>
        <% if @settings.admin.link.present? %>    
          <%= link_to author, @settings.admin.link, target: '_blank' %>
        <% else %>
          <%= author %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

<div class="span3">
  <div class="well well-small">
    <ul class="nav nav-list">
      <li class="nav-header">
        <%= link_to posts_path(format: :atom) do %>
          <%= t(:recent_posts) %>
          <i class="icon-rss"></i>
        <% end %>
      </li>
      <li class="divider"></li>

      <% @recent_posts.each do |post| %>
      <li><%= link_to "#{post.title(current_lang)} (#{post.comments.current(current_lang).count})", post %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="span3">
  <div class="well well-small">
    <ul class="nav nav-list">
      <li class="nav-header">
        <%= t(:categories) %>
      </li>
      <li class="divider"></li>

      <% @categories.each do |category| %>
      <li><%= link_to "#{category.name(current_lang)} (#{category.posts.count})", category %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="span3">
  <div class="well well-small">
    <ul class="nav nav-list">
      <li class="nav-header">
        <%= link_to(t(:tags), :tags) %>
      </li>
      <li class="divider"></li>

      <% @top_tags.each do |tag| %>
      <li><%= link_to "#{tag[:name]} (#{tag[:count]})", tag_path(tag[:name]) %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="span3">
  <div class="well well-small">
    <ul class="nav nav-list">
      <li class="nav-header">
        <%= t(:recent_comments) %>
      </li>
      <li class="divider"></li>

      <% @comments.each do |comment| %>
      <li><%= link_to t('comment', post: comment.post.title(current_lang), author: comment.author), comment.post %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="span3">
  <div class="well well-small">
    <ul class="nav nav-list">
      <li class="nav-header"><%= t(:admin) %></li>
      <li class="divider"></li>

      <% if user_signed_in? %>
        <%= render 'shared/admin_menu' %>
      <% else %>
        <li><%= link_to t(:sign_in), :sign_in %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_aside_stacked.html.erb
<div class="span3">
  <div>
    <h4>
      <%= t(:author) %>
    </h4>
    <ul class="nav nav-tabs nav-stacked">
      <li>
        <% if @settings.admin.link.present? %>    
          <%= link_to author, @settings.admin.link, target: '_blank' %>
        <% else %>
          <%= author %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

<div class="span3">
  <div>
    <h4>
      <%= t(:recent_posts) %>
      <small>
        <%= link_to posts_path(format: :atom) do %>
          <i class="icon-rss"></i>
        <% end %>
      </small>
    </h4>
    <ul class="nav nav-tabs nav-stacked">
      <% @recent_posts.each do |post| %>
      <li><%= link_to "#{post.title(current_lang)} (#{post.comments.current(current_lang).count})", post %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="span3">
  <div>
    <h4>
      <%= t(:categories) %>
    </h4>
    <ul class="nav nav-tabs nav-stacked">
      <% @categories.each do |category| %>
      <li><%= link_to "#{category.name(current_lang)} (#{category.posts.count})", category %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="span3">
  <div>
    <h4>
      <%= link_to(t(:tags), :tags) %>
    </h4>
    <ul class="nav nav-tabs nav-stacked">
      <% @top_tags.each do |tag| %>
      <li><%= link_to "#{tag[:name]} (#{tag[:count]})", tag_path(tag[:name]) %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="span3">
  <div>
    <h4>
      <%= t(:recent_comments) %>
    </h4>
    <ul class="nav nav-tabs nav-stacked">
      <% @comments.each do |comment| %>
      <li><%= link_to t('comment', post: comment.post.title(current_lang), author: comment.author), comment.post %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="span3">
  <div>
    <h4>
      <%= t(:admin) %>
    </h4>
    <ul class="nav nav-tabs nav-stacked">
      <% if user_signed_in? %>
        <%= render 'shared/admin_menu' %>
      <% else %>
        <li><%= link_to t(:sign_in), :sign_in %></li>
      <% end %>
    </ul>
  </div>
</div>