config/routes.rb
Konnyaku::Application.routes.draw do

  root 'welcome#index'

  controller :welcome do
    get :index
    get :dashboard
    get :search
  end

  controller :sessions do
    get :sign_in, action: :new
    post :sessions, action: :create
    delete :sign_out, action: :destroy
  end

  resources :categories
  resources :posts do
    post :markdown, on: :collection
    resources :comments, only: [:create, :destroy]
    resources :versions, only: [:index, :show]
  end
  resources :tags, only: [:index, :show]

  resources :files, only: [:index, :create, :destroy], controller: :uploads, as: :uploads

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :category
  has_many :contents, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :contents

  validates_presence_of :category_id
  validates :slug, uniqueness: true, presence: true, parameterizable: true
  validate :contents_cannot_be_blank

  before_validation :set_slug

  scope :index, -> lang { 
    where('contents.lang_id = ?', lang.id)
    .where('contents.title != ?', '')
    .where('contents.body != ?', '')
    .order('created_at DESC')
    .joins(:contents) 
  } 

  def content(lang)
    current = self.contents.find_by(lang_id: lang.id)
    primary = self.contents.find_by(lang_id: Lang.primary.id)
    if current.try(:title).blank? || current.try(:body).blank?
      return primary 
    else
      return current
    end
  end

  def title(lang)
    current_or_primary(lang, :title)
  end

  def html(lang)
    current_or_primary(lang, :html)
  end
  
  def tags(lang)
    self.contents.find_by(lang_id: lang.id).try(:tags) || []
  end

  def versions(lang)
    versions = self.contents.find_by(lang_id: lang.id).try(:versions) || Version.none
    return versions.where.not(object: nil)
  end

  def langs
    self.contents.where.not(title: '').where.not(body: '').order(:lang_id).map { |c| c.lang }
  end

  def to_param
    self.slug
  end

  def self.search(query, lang)

    query = query.to_s
    query.strip!
    return Post.none if query.blank?

    queries = self.split_query(query)
    conds = self.build_conds(queries)

    posts = self.index(lang).where(conds).joins(:contents).uniq
    return posts
  end

  def self.split_query(q)
    return [] if q.blank?
    q.split(/[\s　]+/)
  end

  def self.build_conds(queries)
    post_table = Post.arel_table
    content_table = Content.arel_table

    conds = nil
    queries.each do |q|
      pattern = "%#{q}%"
      likes = [
        post_table[:slug].matches(pattern),
        content_table[:title].matches(pattern),
        content_table[:body].matches(pattern)
      ] 
      likes.each do |like|
        conds = conds.present? ? conds.or(like) : like
      end
    end
    return conds
  end

  def self.tagged(name, lang)
    name = name.to_s
    name.strip!
    return Post.none if name.blank?
    posts = Post.index(lang).where("contents.tags && ?", "{#{name}}") 
    return posts
  end

private

  def current_or_primary(lang, attr)
    self.contents.find_by(lang_id: lang.id).try(attr).presence || self.contents.find_by(lang_id: Lang.primary.id).try(attr)
  end

  def set_slug
    if self.slug.blank?
      self.slug = self.contents.first.title.to_s.parameterize 
    end
  end

   def contents_cannot_be_blank
    self.errors.add(:contents, :blank) if self.contents.blank?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :sign_in_required, except: [:index, :show]
  before_action :redirect_to_primary, only: [:show, :edit]
  skip_before_action :enable_sidebar, only: [:new, :create, :edit, :update]

  def index
    @paginated_posts = Post.index(current_lang).page(params[:p]).per(@settings.view.pagination.admin)
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
    Lang.all.each do |lang|
      content =  @post.contents.build
      content.lang = lang 
    end
    stringify_tags
  end

  def edit
    Lang.all.each do |lang|
      unless @post.contents.exists?(lang_id: lang.id)
        content =  @post.contents.build
        content.lang = lang 
      end
    end
    @post.updated_at = Time.now
    stringify_tags
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: I18n.t('flash.models.create', model: Post.model_name.human) 
    else
      stringify_tags
      render action: 'new'
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: I18n.t('flash.models.update', model: Post.model_name.human) 
    else
      stringify_tags
      render action: 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to :posts, notice: I18n.t('flash.models.destroy', model: Post.model_name.human) 
  end

  def markdown
    content = Content.new(body: params[:body])
    render text: content.render.to_s, content_type: 'text/html'
  end

private
  def set_post
    @post = Post.find_by!(slug: params[:id])
  end

  def post_params
    parse_tags
    params.require(:post).permit(:category_id, :slug, :created_at, :updated_at, contents_attributes: [:lang_id, :title, :body, :tags, :id])
  end

  def redirect_to_primary
    unless @post.langs.include?(current_lang)
      if params[:action] != 'edit'
        redirect_to post_url(@post, l: Lang.primary.code)
      else
        redirect_to edit_post_url(@post, l: Lang.primary.code)
      end
    end
  end

  def stringify_tags
    @post.contents.each do |content|
      content.tags = content.tags.to_a.join(',')
    end
  end

  def parse_tags
    params[:post][:contents_attributes].each do |i, content|
      params[:post][:contents_attributes][i][:tags] = "{#{content[:tags].split(/,/).map { |t| t.strip }.join(',')}}"
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def lang_list(post, labeled: true)
    list = ''
    post.langs.each do |lang|
      label = labeled ? "<span class=\"label\">#{t(lang.code)}</span>".html_safe : t(lang.code)
      list << "<li class=\"#{lang == current_lang ? 'active' : ''}\">#{link_to(label, post_path(post, l: lang.code))}</li>"
    end
    return list.html_safe
  end

  def tag_list(post)
    list = ''
    post.tags(current_lang).each do |tag|
      label = "<span class=\"label\">#{tag}</span>".html_safe
      list << "<li>#{link_to(label, tag_path(tag))}</li>"
    end
    return list.html_safe
  end

  def time_ago(date, plain: false)
    if plain
      return "#{time_ago_in_words(date)}#{t(:ago)}"
    else
      return "<span title=\"#{l(date)}\">#{time_ago_in_words(date)}#{t(:ago)}</span>".html_safe
    end
  end

  def truncate(text)
    return truncate_html(text, length: @settings.view.truncate).html_safe 
  end

  def highlight_queries(text)
    return highlight(text, Post.split_query(@search_form.q))
  end

end

app/views/posts/_form.html.erb
<%= form_for(@post, html: { class: '' }) do |f| %>

  <% if @post.errors.any? %>
    <div class="alert alert-error">
      <h2><%= t('activerecord.errors.template.header', model: Post.model_name.human, count: @post.errors.count) %></h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="span4">
      <div class="control-group">
        <%= f.label :category_id, class: 'control-label semantics' %>
        <div class="controls">
          <%= f.select :category_id, Category.all.map { |c| [c.name(current_lang), c.id] } %>
        </div>
      </div>
    </div>
    <div class="span4">
      <div class="control-group">
        <%= f.label :slug, class: 'control-label semantics' %>
        <div class="controls">
          /posts/
          <%= f.text_field :slug, placeholder: t('activerecord.attributes.post.slug') %>
        </div>
      </div>
    </div>
    <div class="span4">
      <div class="pull-right">
        <%= link_to t(:preview), '#', class: 'btn js_post_preview' %>
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
  </div>

  <ul class="nav nav-pills">
    <% @langs.each do |lang| %>
      <li class="<%= 'active' if lang == Lang.primary %>">
        <%= link_to t(lang.code), "##{lang.code}", data: { toggle: 'tab' } %>
      </li>
    <% end %>
  </ul>

  <div class="row">
    <div class="span6">

      <div class="tab-content">

        <% @post.contents.each do |content| %>
          <div class="tab-pane <%= 'active' if content.lang == Lang.primary %>" id="<%= content.lang.code %>">
            <%= f.fields_for :contents, content do |cf| %>  

              <%= cf.hidden_field :lang_id %>

              <% with_locale(content.lang.code) do %>
                <div class="control-group">
                  <%= cf.label :title, class: 'control-label semantics' %>
                  <div class="controls">
                    <%= cf.text_field :title, required: content.lang == Lang.primary, placeholder: t('activerecord.attributes.contents.title'), class: 'span6 js_post_title' %>
                  </div>
                </div>

                <div class="control-group">
                  <%= cf.label :body, class: 'control-label semantics' %>
                  <div class="controls">
                    <%= cf.text_area :body, required: content.lang == Lang.primary, placeholder: "#{t('activerecord.attributes.contents.body')} (#{t('markdown')})", class: 'span6 js_post_body', rows: 20 %>
                  </div>
                </div>

                <div class="control-group">
                  <%= cf.label :tags, class: 'control-label semantics' %>
                  <div class="controls">
                    <%= cf.text_field :tags, placeholder: "#{t('tag')}, #{t('tag')}, ...", class: 'span6 js_post_tags' %>
                  </div>
                </div>

                <% if content.lang != Lang.primary %>
                <div class="control-group">
                  <div class="controls">
                    <%= link_to t(:copy, lang: t(Lang.primary.code)), '#', class: 'btn js_post_copy' %>
                  </div>
                </div>
                <% end %>

              <% end %>

            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="span6">
      <div class="tabbable">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#rendered" data-toggle="tab">rendered</a></li>
          <li><a href="#source" data-toggle="tab">source</a></li>
        </ul>
        <div class="tab-content">

          <div class="tab-pane active" id="rendered">
            <div class="post_rendered js_post_rendered"></div>
          </div>

          <div class="tab-pane" id="source">
            <pre class="post_source js_post_source"></pre>
          </div>

        </div>
      </div>
      
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= link_to t(:preview), '#', class: 'btn js_post_preview' %>
      <span class="help-inline">
        <label class="checkbox">
          <input type="checkbox" class="js_post_realtime"> <%= t('realtime') %>
        </label>
      </span>
    </div>
  </div>

  <div class="row">
    <div class="span6">
      <div class="control-group">
        <%= f.label :created_at, class: 'control-label' %>
        <div class="controls datetime">
          <%= f.datetime_select :created_at %>
        </div>
      </div>
    </div>
    <div class="span6">
      <div class="control-group">
        <%= f.label :updated_at, class: 'control-label' %>
        <div class="controls datetime">
          <%= f.datetime_select :updated_at %>
        </div>
      </div>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to t(:cancel), (@post.new_record? ? :posts : @post), class: 'btn' %>
    </div>
  </div>



<% end %>

<%= render 'links' %>

app/views/posts/_links.html.erb
<% if user_signed_in? %>
  <hr />
  <ul class="unstyled">
    <% if controller.action_name == 'show' %>
      <li>
        <%= link_to edit_post_path(@post) do %>
          <i class="icon-pencil"></i> <%= t(:edit_post) %>
        <% end %>
      </li>
    <% end %>
    <li>
      <%= link_to :new_post do %>
        <i class="icon-plus"></i> <%= t(:new_post) %>
      <% end %>
    </li>
    <% unless current_page?(action: :index) %>
      <li>
        <%= link_to :posts do %>
          <i class="icon-book"></i> <%= t(:list_posts) %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/posts/_post.html.erb
<div class="page-header">
  <h2><%= link_to(highlight_queries(post.title(current_lang)), post) %></h2>
</div>

<ul class="unstyled inline">
  <li><%= time_ago(post.created_at) %></li>
  <li><%= link_to(post.category.name(current_lang), post.category) %></li>
</ul>

<div>
<%= truncate(highlight_queries(post.html(current_lang))) %>
</div>

<p>
  <%= t('comments') %> (<%= post.comments.current(current_lang).count %>)
</p>

<hr />

app/views/posts/edit.html.erb
<% title = t(:edit_post) %>
<% content_for(:title) { title } %>

<div class="page-header">
  <h1><%= title %></h1>
</div>

<%= render 'form' %>

app/views/posts/index.html.erb
<% title = t(:list_posts) %>
<% content_for(:title) { title } %>

<div class="page-header">
  <h1><%= title %></h1>
</div>

<table class="table-condensed <%= 'table table-striped table-hover' if user_signed_in? %>">
  <tbody>
    <% @paginated_posts.each do |post| %>
    <tr>
      <td><%= link_to "#{post.title(current_lang)}", post %></td>


      <td><%= link_to(post.category.name(current_lang), post.category) %></td>

      <td>
        <ul class="unstyled inline">
          <%= lang_list(post) %>
        </ul>
      </td>
    
      <% if user_signed_in? %>
      <td>
        <div class="btn-group">
        <%= link_to edit_post_path(post), class: 'btn btn-small', title: t(:edit) do %>
          <i class="icon-pencil"></i>
          <%= t(:edit) %>
        <% end %>

        <%= link_to post, method: :delete, data: { confirm: t(:sure) }, class: 'btn btn-danger btn-small', title: t(:delete) do %>
          <i class="icon-remove"></i>
          <%= t(:delete) %>
        <% end %>

        </div>
      </td>
      <% end %>

    </tr>
    <% end %>
  </tbody>
</table>

<%= page_entries_info(@paginated_posts, entry_name: Post.model_name.human) %>
<%= paginate @paginated_posts, param_name: :p %>

<%= render 'links' %>

app/views/posts/new.html.erb
<% title = t(:new_post) %>
<% content_for(:title) { title } %>

<div class="page-header">
  <h1><%= title %></h1>
</div>

<%= render 'form' %>

app/views/posts/show.html.erb
<% title = @post.title(current_lang) %>
<% content_for(:title) { title } %>

<ul class="nav nav-pills">
  <%= lang_list(@post, labeled: false) %>
</ul>

<div class="page-header">
  <h1><%= link_to(title, @post) %></h1>
</div>

<div class="row">
  <div class="span3">
    <p>
      <%= link_to(@post.category.name(current_lang), @post.category) %>
    </p>
  </div>
  <div class="span3">
    <p>
      <%= t(:created_at) %> 
      <%= time_ago(@post.created_at) %>
    </p>
  </div>
  <div class="span3">
    <p>
      <%= t(:updated_at) %>
      <%= time_ago(@post.updated_at) %>
    </p>
  </div>
</div>

<ul class="unstyled inline">
  <%= tag_list(@post) %>
</ul>

<%= @post.html(current_lang).html_safe %>

<div class="row">
  <div class="span1">
    <p>
      <a href="https://twitter.com/share" class="twitter-share-button" data-dnt="true" data-count="vertical">Tweet</a>
    </p>
  </div>
  <div class="span1">
    <div class="fb-like" data-send="false" data-layout="box_count" data-width="150" data-show-faces="false"></div>
  </div>
</div>

<% if @post.versions(current_lang).present? %>
<p>
  <%= link_to("#{t('histories')} (#{@post.versions(current_lang).length})", post_versions_path(@post)) %>
</p>
<% end %>

<%= render 'posts/links' %>

<hr />

<p>
  <%= t('comments') %> (<%= @post.comments.current(current_lang).count %>)
</p>

<dl>
<%= render @post.comments.current(current_lang) %>
</dl>

<%= render 'comments/form' %>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>