config/routes.rb
Konnyaku::Application.routes.draw do

  root 'welcome#index'

  controller :welcome do
    get :index
    get :dashboard
    get :search
  end

  controller :sessions do
    get :sign_in, action: :new
    post :sessions, action: :create
    delete :sign_out, action: :destroy
  end

  resources :categories
  resources :posts do
    post :markdown, on: :collection
    resources :comments, only: [:create, :destroy]
    resources :versions, only: [:index, :show]
  end
  resources :tags, only: [:index, :show]

  resources :files, only: [:index, :create, :destroy], controller: :uploads, as: :uploads

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :posts

  validates :slug, uniqueness: true, presence: true, parameterizable: true
  validate :name_of_primary_lang_cannot_be_blank
  before_validation :set_slug
  before_destroy :move_to_default

  def name(lang)
    n = self.names[lang.code]
    n.present? ? n : self.names[Lang.primary.code]
  end

  def to_param
    "#{self.slug}"
  end

  def self.default
    self.first
  end

private

  def set_slug
    if self.slug.blank?
      code = Lang.primary.code
      self.slug = (self.names[code] || self.names[code.to_sym]).parameterize 
    end
  end

  def name_of_primary_lang_cannot_be_blank
    code = Lang.primary.code
    self.errors.add(:names, :blank) if (self.names[code] || self.names[code.to_sym]).blank? 
  end

  def move_to_default
    self.posts.each do |post|
      post.category = Category.default 
      post.save!
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :sign_in_required, except: [:index, :show]

  def index
    # Load in ApplicationController#load_categories
  end

  def show
    @paginated_posts = @category.posts.page(params[:p]).per(@settings.view.pagination.recent)
  end

  def new
    @category = Category.new
    @category.names = {}
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.names = params[:category][:names]

    if @category.save
      redirect_to :categories, notice: I18n.t('flash.models.create', model: Category.model_name.human) 
    else
      render action: 'new'
    end
  end

  def update
    @category.names = params[:category][:names]
    if @category.update(category_params)
      redirect_to :categories, notice: I18n.t('flash.models.update', model: Category.model_name.human) 
    else
      render action: 'edit'
    end
  end

  def destroy
    if @category == @categories.first 
      redirect_to :categories 
      return
    end

    @category.destroy
    redirect_to :categories, notice: I18n.t('flash.models.destroy', model: Category.model_name.human) 
  end

private
  def set_category
    @category = Category.find_by!(slug: params[:id])
  end

  def category_params
    params.require(:category).permit(:names, :slug)
 end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, html: { class: 'form-horizontal' }) do |f| %>

  <% if @category.errors.any? %>
    <div class="alert alert-error">
      <h2><%= t('activerecord.errors.template.header', model: Category.model_name.human, count: @category.errors.count) %></h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :names, class: 'control-label' %>
    <div class="controls">

      <div class="tabbable tabs-below">
        <div class="tab-content">
          <% @langs.each do |lang| %>
            <div class="tab-pane <%= 'active' if lang == Lang.primary %>" id="<%= lang.code %>">
              <p>
              <%= text_field_tag "category[names][#{lang.code}]", @category.names[lang.code], required: (lang == @langs.first), autofocus: (lang == @langs.first) %>
              </p>
            </div>
          <% end %>
        </div>
        <ul class="nav nav-pills">
          <% @langs.each do |lang| %>
            <li class="<%= 'active' if lang == Lang.primary %>">
              <%= link_to t(lang.code), "##{lang.code}", data: { toggle: 'tab' } %>
            </li>
          <% end %>
        </ul>
      </div>

    </div>
  </div>

  <div class="control-group">
    <%= f.label :slug, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :slug %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to t(:cancel), :categories, class: 'btn' %>
    </div>
  </div>

<% end %>

<%= render 'links' %>

app/views/categories/_links.html.erb
<% if user_signed_in? %>
  <hr />
  <ul class="unstyled">
    <% if controller.action_name == 'show' %>
      <li>
        <%= link_to edit_category_path(@category) do %>
          <i class="icon-pencil"></i> <%= t(:edit_category) %>
        <% end %>
      </li>
    <% end %>
    <li>
      <%= link_to :new_category do %>
        <i class="icon-plus"></i> <%= t(:new_category) %>
      <% end %>
    </li>
    <% unless current_page?(action: :index) %>
      <li>
        <%= link_to :categories do %>
          <i class="icon-folder-open-alt"></i> <%= t(:list_categories) %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/categories/edit.html.erb
<% title = t(:edit_category) %>
<% content_for(:title) { title } %>

<div class="page-header">
  <h1><%= title %></h1>
</div>

<%= render 'form' %>

app/views/categories/index.html.erb
<% title = t(:list_categories) %>
<% content_for(:title) { title } %>

<div class="page-header">
  <h1><%= title %></h1>
</div>

<table class="table-condensed <%= 'table table-striped table-hover' if user_signed_in? %>">
  <tbody>
    <% @categories.each do |category| %>
    <tr>
      <td><%= link_to "#{category.name(current_lang)} (#{category.posts.count})", category %></td>
    
      <% if user_signed_in? %>
      <td>
        <div class="btn-group">
        <%= link_to edit_category_path(category), class: 'btn btn-small', title: t(:edit) do %>
          <i class="icon-pencil"></i>
          <%= t(:edit) %>
        <% end %>

        <% if category != @categories.first %>
        <%= link_to category, method: :delete, data: { confirm: t(:sure) }, class: 'btn btn-danger btn-small', title: t(:delete) do %>
          <i class="icon-remove"></i>
          <%= t(:delete) %>
        <% end %>
        <% end %>

        </div>
      </td>
      <% end %>

    </tr>
    <% end %>
  </tbody>
</table>

<%= render 'links' %>

app/views/categories/new.html.erb
<% title = t(:new_category) %>
<% content_for(:title) { title } %>

<div class="page-header">
  <h1><%= title %></h1>
</div>

<%= render 'form' %>

app/views/categories/show.html.erb
<% title = "#{@category.name(current_lang)} #{@settings.site.dot} #{t(:categories)}" %>
<% content_for(:title) { title } %>

<div class="page-header">
  <h1><%= @category.name(current_lang) %></h1>
</div>

<%= render @paginated_posts %>

<%= page_entries_info(@paginated_posts, entry_name: Post.model_name.human) %>
<%= paginate @paginated_posts, param_name: :p %>

<%= render 'links' %>